language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - extra-google-google_play_services
  licenses:
    - '.+'
before_script:
    - mkdir libs
    - wget -O libs/libwebrtc-m89.aar https://gultsch.de/files/libwebrtc-m89.aar
script:
    - ./gradlew assembleQuicksyFreeCompatDebug
    - ./gradlew assembleQuicksyFreeSystemDebug
    - ./gradlew assembleConversationsFreeCompatDebug
    - ./gradlew assembleConversationsFreeSystemDebug

before_install:
    - yes | sdkmanager "platforms;android-28"
