language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - build-tools-23.0.0
    - build-tools-22.0.1
    - build-tools-21.1.2
    - build-tools-19.1.0
    - android-23
    - extra-android-m2repository
